import type { CompositionTemplate } from '../../types/thumbnail'

export const PRESET_TEMPLATES: CompositionTemplate[] = [
  {
    id: 'side-by-side',
    name: 'Dual Speaker Debate',
    description: 'Balanced side-by-side layout with bold centered headline',
    backgroundTransform: { x: 0, y: 0, scaleX: 1, scaleY: 1 },
    speaker1Transform: {
      x: 320,
      y: 440,
      scaleX: 0.9,
      scaleY: 0.9,
      rotation: 0,
      flipX: false,
    },
    speaker2Transform: {
      x: 960,
      y: 440,
      scaleX: 0.9,
      scaleY: 0.9,
      rotation: 0,
      flipX: false,
    },
    textStyleAndPosition: {
      fontFamily: 'Montserrat',
      fontSize: 70,
      fontWeight: '900',
      textAlign: 'center',
      fillColor: '#FACC15', // Vibrant yellow
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowBlur: 16,
      shadowOffsetX: 4,
      shadowOffsetY: 6,
      transform: {
        x: 640,
        y: 100,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
      },
      visible: true,
    },
  },
  {
    id: 'host-guest-spotlight',
    name: 'Host & Guest Spotlight',
    description: 'Prominent guest on right, host on left with angled headline',
    backgroundTransform: { x: 0, y: 0, scaleX: 1, scaleY: 1 },
    speaker1Transform: {
      x: 260,
      y: 460,
      scaleX: 0.8,
      scaleY: 0.8,
      rotation: -3,
      flipX: false,
    },
    speaker2Transform: {
      x: 980,
      y: 410,
      scaleX: 1.05,
      scaleY: 1.05,
      rotation: 2,
      flipX: false,
    },
    textStyleAndPosition: {
      fontFamily: 'Bebas Neue',
      fontSize: 84,
      fontWeight: 'bold',
      textAlign: 'center',
      fillColor: '#FFFFFF',
      strokeColor: '#DC2626', // Bold red outline
      strokeWidth: 5,
      shadowColor: 'rgba(0, 0, 0, 0.85)',
      shadowBlur: 14,
      shadowOffsetX: 3,
      shadowOffsetY: 5,
      transform: {
        x: 640,
        y: 110,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
      },
      visible: true,
    },
  },
  {
    id: 'dramatic-clash',
    name: 'Dramatic Clash',
    description: 'Overlapping centered speakers with high-impact uppercase headline',
    backgroundTransform: { x: 0, y: 0, scaleX: 1, scaleY: 1 },
    speaker1Transform: {
      x: 440,
      y: 430,
      scaleX: 0.95,
      scaleY: 0.95,
      rotation: -4,
      flipX: false,
    },
    speaker2Transform: {
      x: 840,
      y: 430,
      scaleX: 0.95,
      scaleY: 0.95,
      rotation: 4,
      flipX: false,
    },
    textStyleAndPosition: {
      fontFamily: 'Montserrat',
      fontSize: 76,
      fontWeight: '900',
      textAlign: 'center',
      fillColor: '#38BDF8', // Sky blue
      strokeColor: '#0F172A',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowBlur: 20,
      shadowOffsetX: 4,
      shadowOffsetY: 8,
      transform: {
        x: 640,
        y: 95,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
      },
      visible: true,
    },
  },
]
